name: Guvenli Gelistirme Hatti
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  kontrol-merkezi:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Kopyala
        uses: actions/checkout@v4

      - name: Otomatik Testleri Calistir
        run: |
          echo "Sistem: Eski versiyonlar kontrol ediliyor..."
          echo "Sistem: Yeni eklenenler test ediliyor. Bozulma yoksa onay verilecek."